version 0.2.0

diff --git a/src/libmoocore/Makefile b/src/libmoocore/Makefile
--- a/src/libmoocore/Makefile
+++ b/src/libmoocore/Makefile
@@ -1,7 +1,7 @@
 #-----------------------------------------------------------------------
 #  Makefile for moocore
 #-----------------------------------------------------------------------
-VERSION = 0.17.0
+VERSION = 0.18
 
 S=
 ## Quiet / verbose output:
@@ -96,6 +96,7 @@ HDRS =  avl.h                                                                \
         hvapprox.h                                                           \
         hv_priv.h                                                            \
         hv3d_priv.h                                                          \
+        hv4d_priv.h                                                          \
         igd.h                                                                \
         io.h                                                                 \
         io_priv.h                                                            \
@@ -116,12 +117,10 @@ DIST_ROOT_FILES = Makefile README.md LICENSE
 OBJS  = $(SRCS:.c=.o)
 OBJS := $(OBJS:.cpp=.o)
 
-EXE_LDFLAGS=-lm
+LDLIBS=-lm
+EXE_LDFLAGS=$(LDLIBS)
 
 include gitversion.mk
-
-# mex
-MEX?=mkoctfile --mex
 
 ifneq ($(uname_S),Cygwin)
 CPPFLAGS += -D_GNU_SOURCE
@@ -135,12 +134,12 @@ SHLIB_LDFLAGS = -shared
 # Platform-specific linker flags
 ifeq ($(uname_S),Linux)
   SHLIB_CFLAGS += -fPIC
-  SHLIB_LDFLAGS += -lm -Wl,--no-undefined
+  SHLIB_LDFLAGS += $(LDLIBS) -Wl,--no-undefined
   SHLIB_EXT=so
 endif
 ifeq ($(uname_S),Darwin)
   SHLIB_CFLAGS += -fPIC
-  SHLIB_LDFLAGS += -lm
+  SHLIB_LDFLAGS += $(LDLIBS)
   SHLIB_EXT=dylib
 endif
 ifeq ($(uname_S),Windows)
@@ -156,19 +155,20 @@ EXE_CFLAGS += $(SANITIZERS) $(OPT_CFLAGS) $(MARCH_FLAGS) $(WARN_CFLAGS) \
 
 
 # List of test target base names
-TEST_NAMES := eaf nondominated hv hvapprox igd epsilon dominatedsets
+TEST_NAMES := eaf nondominated hv hvapprox igd epsilon dominatedsets ndsort
+ASAN_TARGETS := $(addprefix asan-,$(TEST_NAMES))
 TEST_TARGETS := $(addprefix test-,$(TEST_NAMES))
 TIME_TARGETS := $(addprefix time-,$(TEST_NAMES))
-ALL_NAMES := $(TEST_NAMES) ndsort
+ALL_NAMES := $(TEST_NAMES)
 
 EXE_FILES := $(addsuffix $(EXE), $(addprefix $(BINDIR)/,$(ALL_NAMES)))
 
 SHLIB=libmoocore.$(SHLIB_EXT)
 CXXSHLIB=libmoocorepp.$(SHLIB_EXT)
 
-default: $(EXE_FILES)
-
 .PHONY : all clean default dist $(ALL_NAMES) test time shlibs
+
+default: $(EXE_FILES)
 
 all: clean
 	$(MAKE) default
@@ -195,38 +195,45 @@ $(BINDIR)/nondominated$(EXE): nondominated.o timer.o
 $(EXE_FILES): cmdline.o io.o
 	$(call MKDIR, $(BINDIR)/)
 	$(call ECHO,--> Building $@ version $(VERSION) <---)
-	$(QUIET_LINK)$(CC) -o $@ $^ $(EXE_CFLAGS) $(CFLAGS) $(EXE_LDFLAGS)
+	$(QUIET_LINK)$(CC) -o $@ $^ $(EXE_CFLAGS) $(CFLAGS) $(EXE_LDFLAGS) $(LDFLAGS)
 
-dominatedsets.o: cmdline.h io.h nondominated.h
-eaf_main.o: cmdline.h io.h eaf.h
-epsilon.o: cmdline.h io.h epsilon.h nondominated.h
-main-hv.o: cmdline.h io.h hv.h timer.h
-ndsort.o: cmdline.h io.h nondominated.h
-nondominated.o : cmdline.h io.h nondominated.h
-main-hvapprox.o: cmdline.h io.h hvapprox.h
-hvapprox.o: hvapprox.h pow_int.h
-timer.o: timer.h
-eaf.o eaf3d.h: eaf.h
-cmdline.o: cmdline.h io.h
-io.o: io_priv.h io.h
-igd.o : cmdline.h io.h igd.h
 avl.o: avl.h
-$(OBJS): common.h gcc_attribs.h
+cmdline.o: cmdline.h io.h
+dominatedsets.o: cmdline.h io.h nondominated.h sort.h avl_tiny.h epsilon.h
+eaf.o: eaf.h io.h bit_array.h cvector.h
+eaf3d.o: eaf.h io.h bit_array.h cvector.h avl.h
+eaf_main.o: cmdline.h io.h eaf.h bit_array.h cvector.h
+epsilon.o: cmdline.h io.h epsilon.h nondominated.h sort.h avl_tiny.h
+hv.o: hv.h hv_priv.h hv4d_priv.h sort.h libmoocore-config.h
+hv3dplus.o: hv_priv.h sort.h hv3d_priv.h avl_tiny.h
+hv4d.o: hv4d_priv.h hv_priv.h sort.h
+hv_contrib.o: hv.h libmoocore-config.h nondominated.h sort.h avl_tiny.h
+hvapprox.o: hvapprox.h pow_int.h rng.h mt19937/mt19937.h
+hvc3d.o: hv_priv.h sort.h hv3d_priv.h avl_tiny.h
+igd.o: cmdline.h io.h igd.h nondominated.h sort.h avl_tiny.h pow_int.h
+io.o: io.h io_priv.h
+main-hv.o: cmdline.h io.h hv.h timer.h libmoocore-config.h nondominated.h sort.h avl_tiny.h hvapprox.h
+main-hvapprox.o: cmdline.h io.h hvapprox.h
+ndsort.o: cmdline.h io.h nondominated.h sort.h avl_tiny.h hv.h
+nondominated.o : cmdline.h io.h nondominated.h avl_tiny.h
+pareto.o: nondominated.h sort.h avl_tiny.h
+rng.o: rng.h mt19937/mt19937.h ziggurat_constants.h
+timer.o: timer.h
+$(OBJS): common.h gcc_attribs.h config.h maxminclamp.h
 
 shlibs: clean $(SHLIB) $(CXXSHLIB)
 
 $(SHLIB): CFLAGS += $(SHLIB_CFLAGS)
 $(SHLIB): $(LIBHV_OBJS)
-	$(CC) $(CFLAGS) $(CPPFLAGS) $(LDFLAGS) -o $@ $^ $(SHLIB_LDFLAGS)
+	$(QUIET_CC)$(CC) $(CFLAGS) $(CPPFLAGS) $(LDFLAGS) -o $@ $^ $(SHLIB_LDFLAGS)
 
 $(CXXSHLIB): CFLAGS += $(SHLIB_CFLAGS)
 $(CXXSHLIB): $(LIBHV_OBJS)
-	$(CXX) $(CFLAGS) $(CPPFLAGS) $(LDFLAGS) -o $@ $^ $(SHLIB_LDFLAGS)
+	$(QUIET_CXX)$(CXX) $(CFLAGS) $(CPPFLAGS) $(LDFLAGS) -o $@ $^ $(SHLIB_LDFLAGS)
 
 clean:
-	@-$(RM) *.s *.i
+	@-$(RM) *.s *.i *.gcda mt19937/*.gcda
 	@-$(RM) config.status config.log
-	@-$(RM) Hypervolume_MEX.mex
 	@-$(RM) $(SHLIB) $(CXXSHLIB)
 	@for exe in $(EXE_FILES); do \
 		echo "---> Removing $$exe <---"; \
@@ -236,6 +243,27 @@ clean:
 	@$(RM) $(OBJS) $(HV_OBJS) $(HV_LIB)
 
 TESTSUITE:="../testsuite"
+asan: OPT_CFLAGS ?=-Og -g3
+asan: SANITIZERS ?=$(DEFAULT_SANITIZERS)
+asan:
+	@if ! test -d $(TESTSUITE); then  		    	         \
+	    echo "Error: Testsuite not found in $(TESTSUITE)" && exit 1; \
+	fi
+	$(MAKE) all DEBUG=1 SANITIZERS="$(SANITIZERS)" OPT_CFLAGS="$(OPT_CFLAGS)"
+	$(MAKE) $(ASAN_TARGETS)
+
+$(ASAN_TARGETS): target=$(subst asan-,,$@)
+$(ASAN_TARGETS): OPT_CFLAGS ?=-Og -g3
+$(ASAN_TARGETS): SANITIZERS ?=$(DEFAULT_SANITIZERS)
+$(ASAN_TARGETS):
+	$(MAKE) $(target) DEBUG=1 SANITIZERS="$(SANITIZERS)" OPT_CFLAGS="$(OPT_CFLAGS)"
+	$(call ECHO,---> Testing $(target) for errors (DEBUG=1, $(SANITIZERS)) <--- )
+
+	@cd $(TESTSUITE)/$(target) && \
+	export ASAN_OPTIONS='detect_leaks=0:strict_string_checks=1:detect_stack_use_after_return=1:check_initialization_order=1:strict_init_order=1:detect_invalid_pointer_pairs=2:abort_on_error=1' && \
+	export UBSAN_OPTIONS='print_stacktrace=1:halt_on_error=1' && \
+	../regtest.py $(BINDIR)/$(target)$(EXE) && cd $(PWD)
+
 test: OPT_CFLAGS ?=-Og -g3
 test: SANITIZERS ?=
 test:
@@ -265,10 +293,6 @@ $(TIME_TARGETS):
 	$(MAKE) $(target) DEBUG=0 SANITIZERS=""
 	$(call ECHO,---> Testing $(target) for speed (DEBUG=0) <--- )
 	@cd $(TESTSUITE)/$(target) && ../regtest.py $(BINDIR)/$(target)$(EXE) && cd $(PWD)
-
-mex: Hypervolume_MEX.c $(LIBHV_OBJS)
-	$(call ECHO,---> You can use 'make mex MEXFLAGS="-O -std=c99"' to pass flags to mex. Code compiled by mex is less optimized (slower) than the default 'hv' command-line program <---)
-	$(MEX) -v $(MEXFLAGS) -std=c99 $^
 
 DIST_SRC_FILES = $(DIST_OTHER_FILES) $(SRCS) $(HDRS)
 DIST_SRC:= moocore-$(VERSION)-src
